/*
-- =================================================================================
-- 0. 정리용
-- =================================================================================
DROP TABLE IF EXISTS codes CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS usage_groups CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS distributions CASCADE;
DROP TABLE IF EXISTS distribution_info CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS devices_log CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP FUNCTION IF EXISTS get_my_organization_path;
*/


-- =================================================================================
-- Enums
-- =================================================================================

-- 권한
CREATE TYPE user_role AS ENUM (
    'SYSTEM_ADMIN',  -- 전체 관리자
    'SYSTEM_VIEWER', -- 전체 조회자
    'REGION_ADMIN',  -- 지역 관리자
    'REGION_VIEWER', -- 지역 조회자
    'ORG_ADMIN',     -- 조직(학교) 관리자
    'ORG_VIEWER'     -- 조직(학교) 조회자
);

-- 승인 상태
CREATE TYPE approval_status AS ENUM (
    'PENDING',   -- 승인 대기
    'APPROVED',  -- 승인 완료
    'REJECTED',  -- 승인 거절
    'SUSPENDED'  -- 계정 중지
);

--
CREATE TYPE action_type AS ENUM (
    'UPDATE',
    'DELETE'
);

-- =================================================================================
-- Common Trigger - updated_at
-- =================================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


-- =================================================================================
-- Table Definition
-- =================================================================================

-- [Table] 1. 코드
CREATE TABLE codes (
    code TEXT PRIMARY KEY,          -- 예: 'STS_NORMAL', 'ACT_REPAIR', 'APV_PENDING'
    group_code TEXT NOT NULL REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE, -- 프론트엔드 노출 여부 (삭제 대신 false)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_codes_updated_at
    BEFORE UPDATE ON codes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- [Table] 2. 조직도
-- parent_id(계층)와 path_string(경로 탐색)을 혼합 사용
CREATE TABLE organizations (
    code TEXT PRIMARY KEY,          -- 예: 'SCH001'
    org_type_code TEXT REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE, -- 기관 구분
    name TEXT NOT NULL,
    is_managed BOOLEAN DEFAULT TRUE,    -- 기기 관리 여부
    parent_code TEXT REFERENCES organizations(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    
    -- [성능 최적화] ltree를 이용한 계층 구조 관리
    -- 예: 'ROOT.A123456789.B987654321'
    path LTREE,
    
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
-- path 계산 트리거 있음

-- [Table] 3. 기기 사용 그룹
CREATE TABLE usage_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT REFERENCES organizations(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_usage_groups_updated_at
    BEFORE UPDATE ON usage_groups
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- [Table] 4. 기기 모델
CREATE TABLE models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code TEXT NOT NULL REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    name TEXT NOT NULL,         -- 예: '갤럭시 탭 S7 FE'
    model_number TEXT,          -- 예: 'SM-T733'
    spec TEXT,
    display NUMERIC,
    os_code TEXT NOT NULL REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    price BIGINT DEFAULT 0,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_models_updated_at
    BEFORE UPDATE ON models
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- [Table] 5. 보급 차수
CREATE TABLE distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    dist_code TEXT NOT NULL REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE, 
    name TEXT NOT NULL,
    description TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_distributions_updated_at
    BEFORE UPDATE ON distributions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- [Table] 6. 보급 차수 부가 정보
CREATE TABLE distribution_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_id BIGINT NOT NULL REFERENCES distributions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    organization_code TEXT REFERENCES organizations(code) ON DELETE RESTRICT ON UPDATE CASCADE,

    model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_distribution_info_updated_at
    BEFORE UPDATE ON distribution_info
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- [Table] 7. 기기 정보
-- Update 시 기존 정보를 devices_log 에 넣고, revision을 올림
CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision INTEGER NOT NULL DEFAULT 1,
    
    serial_number TEXT UNIQUE CHECK (serial_number <> ''),  
    mac_address TEXT UNIQUE CHECK (mac_address <> ''),      
    asset_number TEXT UNIQUE CHECK (asset_number <> ''),    
    
    model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    distribution_id BIGINT REFERENCES distributions(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    organization_code TEXT NOT NULL REFERENCES organizations(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    status_code TEXT NOT NULL REFERENCES codes(code) ON DELETE RESTRICT ON UPDATE CASCADE, 
    usage_group_id BIGINT REFERENCES usage_groups(id) ON DELETE RESTRICT ON UPDATE CASCADE,

    metadata JSONB DEFAULT '{}'::JSONB,
    
    -- [추가] Supabase Auth 유저 추적용 컬럼
    created_by UUID DEFAULT AUTH.UID(), -- 생성 시 자동 기록됨
    updated_by UUID DEFAULT AUTH.UID(), -- 생성 시 자동 기록, 이후 트리거가 갱신
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_devices_updated_at
    BEFORE UPDATE ON devices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- [Table] 8. 기기 이력
CREATE TABLE devices_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    revision INTEGER NOT NULL,
    action_type action_type NOT NULL,
    
    action_by UUID, 
    logged_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- 아래는 devices 원본 스냅샷 데이터
    serial_number TEXT,
    mac_address TEXT,
    asset_number TEXT,
    model_id BIGINT,
    distribution_id BIGINT,
    organization_code TEXT,
    status_code TEXT,
    usage_group_id BIGINT,
    metadata JSONB,
    
    created_by UUID, -- 과거 상태의 생성자
    updated_by UUID, -- 과거 상태의 수정자
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);


-- [Table] 9. User profiles
CREATE TABLE profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    organization_code TEXT REFERENCES organizations(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    role user_role NOT NULL DEFAULT 'ORG_VIEWER',
    email TEXT,
    name TEXT,
    task TEXT,                      -- 담당 업무 - 담당 교사, 디지털튜터 등
    rejection_reason TEXT,          -- 거절 사유
    approval_status approval_status DEFAULT 'PENDING',
    approver_id UUID REFERENCES profiles(id) ON UPDATE CASCADE , -- 승인자 ID
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

